spring:
  ssl:
   bundle:
     jks:
       secure-service:
         key:
           alias: "secure-service"
         keystore:
           location: "classpath:keystore.p12"
           password: "Password10$"
           type: "PKCS12"
  data:
    mongodb:
      uri: mongodb://localhost:27017/estate_hub
      
jwt:
  secret: "ca288b9d9b63ad6a7f895c6ebe1f3820cf8dc5c88ea1b64740ab2661a43241cf"

server:
  port: 8443
  ssl:
    bundle: "secure-service"

logging:
  level:
    org.springframework.security: DEBUG
